message-prefix: "[Helden]"
message-prefix-color: "§b"
fireworkCrossbowEnabled: false
allow-punch: false
villagerTradingEnabled: false
loseLifeOnLogoutDuringCombat: false
keepInventoryPercentageCombat: 0.5 #50%
keepInventoryPercentageNatural: 0.0 #00%
dummy:
  enabled: true
  despawn-time: 30 #Sekunden
mendingUsage: no_armor  # Optionen: everything, no_armor, nothing

