name: MinecraftHeroes
main: de.scholle.minecraftheroes.CombatPlugin
version: 2.6
api-version: "1.21"
author: Scholle
description: 3-life combat system

commands:
  lives:
    description: Check or modify player lives
    usage: /lives <check|add|set> <player> [amount]
  heart:
    description: Gib ein Herz, um deinen Partner zu retten
    usage: /heart <player>
  listdummys:
    description: Listet alle aktiven Dummys mit Positionen
  discord:
    description: Zeigt den Discord-Link
  dc:
    description: Zeigt den Discord-Link
  texturepack:
    description: Gibt den Texturepack-Link
  resourcepack:
    description: Gibt den Texturepack-Link
  duel:
    description: Starte ein Duell oder akzeptiere eine Anfrage
    usage: /duel <Spieler> | /duel accept
    aliases: [ duell ]